Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 300
      MemorySize: 128
      Handler: com.axis.handler.App
      CodeUri: /home/prateek/installation/bfsi/java/case_Study/TestLambda2/S3UrlGenerator
      Runtime: java8