package com.axis.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import java.util.ArrayList;
import java.util.List;

@DynamoDBTable(tableName = "InsuranceType")
public class InsuranceType {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String insuranceTypeId;
    private String insuranceTypeName;
    private List<Vendor> listOfVendors = new ArrayList<>();

    public String getInsuranceTypeId() {
        return insuranceTypeId;
    }

    public void setInsuranceTypeId(String insuranceTypeId) {
        this.insuranceTypeId = insuranceTypeId;
    }

    public String getInsuranceTypeName() {
        return insuranceTypeName;
    }

    public void setInsuranceTypeName(String insuranceTypeName) {
        this.insuranceTypeName = insuranceTypeName;
    }

    public List<Vendor> getListOfVendors() {
        return listOfVendors;
    }

    public void setListOfVendors(List<Vendor> listOfVendors) {
        this.listOfVendors = listOfVendors;
    }

    @Override
    public String toString() {
        return "InsuranceType{" +
                "insuranceTypeId='" + insuranceTypeId + '\'' +
                ", insuranceTypeName='" + insuranceTypeName + '\'' +
                ", listOfVendors=" + listOfVendors +
                '}';
    }
}
